services:
  opensearch:
    image: opensearchproject/opensearch:2.17.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - 9200:9200
      - 9600:9600
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    build: .
    container_name: web_app
    ports:
      - 5000:5000
    depends_on:
      opensearch:
        condition: service_healthy
    environment:
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200

volumes:
  opensearch-data: